[project]
name = "ec2-win-pkcs11"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.14",
    "click>=8.2.0",
    "python-pkcs11>=0.7.0",
]
